#!/bin/bash
if [[ -e "provisioning-complete" ]]
then
    echo Looks like this machine is already provisioned. Skipping...
    exit 0
fi
set -ex
apt-add-repository ppa:git-core/ppa
apt-get update
apt-get -y dist-upgrade
apt-get -y install \
    git \
    pandoc \
    ubuntu-desktop
touch "provisioning-complete"
