#!/bin/bash
if [[ -e "provisioning-complete" ]]
then
    echo Looks like this machine is already provisioned. Skipping...
    exit 0
fi
set -ex
apt-add-repository ppa:git-core/ppa
apt-get update
apt-get -y dist-upgrade
apt-get -y install \
    git \
    openjdk-7-jre-headless \
    pandoc \
    ubuntu-desktop \
    vim
HADOOP_VERSION=1.0.4
wget http://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz
tar -xzf hadoop-$HADOOP_VERSION.tar.gz
git clone git://github.com/meonkeys/hadoop-talk.git
echo "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386" >> /home/vagrant/.bashrc
echo "export HADOOP_HOME=/home/vagrant/hadoop-$HADOOP_VERSION" >> /home/vagrant/.bashrc
sed -i 's/enabled=1/enabled=0/' /etc/default/apport
touch "provisioning-complete"
