#!/bin/bash
if [[ -e "/root/provisioning-complete" ]]
then
    echo Looks like this machine is already provisioned. Skipping...
    exit 0
fi
set -ex
apt-add-repository ppa:git-core/ppa
apt-get update
apt-get -y dist-upgrade
apt-get -y install \
    git \
    openjdk-7-jre-headless \
    pandoc \
    tree \
    ubuntu-desktop \
    vim
HADOOP_VERSION=1.0.4
wget http://archive.apache.org/dist/hadoop/core/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz
tar -xzf hadoop-$HADOOP_VERSION.tar.gz
echo "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386" >> /home/vagrant/.bashrc
echo "export HADOOP_PREFIX=/home/vagrant/hadoop-$HADOOP_VERSION" >> /home/vagrant/.bashrc
wget -O ez_setup.py http://bit.ly/ezsetup
python ez_setup.py -z dumbo
sed -i 's/enabled=1/enabled=0/' /etc/default/apport
rm -rf /home/vagrant/{Desktop,Documents,Downloads,Music,Pictures,Public,Templates,Videos}
chown -R vagrant.vagrant /home/vagrant
touch "/root/provisioning-complete"
