# vim: ft=ruby
Vagrant.configure("2") do |config|
    config.vm.box = 'precise32'
    config.vm.box_url = 'http://files.vagrantup.com/precise32.box'
    config.vm.provision :shell, :path => "bootstrap-vm"
    config.vm.provider 'virtualbox' do |v|
	v.gui = true
	v.name = 'lfnw 2013 presentation vm'
    end
end
